export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_REQUEST = 'FETCH_CATEGORY_REQUEST';
export const FETCH_CATEGORY_FAILURE = 'FETCH_CATEGORY_FAILURE';

export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';

export const FETCH_NAVMENU_SUCCESS = 'FETCH_NAVMENU_SUCCESS';
export const FETCH_NAVMENU_REQUEST = 'FETCH_NAVMENU_REQUEST';
export const FETCH_NAVMENU_FAILURE = 'FETCH_NAVMENU_FAILURE';

export const FETCH_BLOG_SUCCESS = 'FETCH_BLOG_SUCCESS';
export const FETCH_BLOG_REQUEST = 'FETCH_BLOG_REQUEST';
export const FETCH_BLOG_FAILURE = 'FETCH_BLOG_FAILURE';

export const FETCH_FAQS_SUCCESS = 'FETCH_FAQS_SUCCESS';
export const FETCH_FAQS_REQUEST = 'FETCH_FAQS_REQUEST';
export const FETCH_FAQS_FAILURE = 'FETCH_FAQS_FAILURE';

export const FETCH_ABOUT_SUCCESS = 'FETCH_ABOUT_SUCCESS';
export const FETCH_ABOUT_REQUEST = 'FETCH_ABOUT_REQUEST';
export const FETCH_ABOUT_FAILURE = 'FETCH_ABOUT_FAILURE';

export const PRODUCT_ADDED_TO_CART = 'PRODUCT_ADDED_TO_CART';
export const PRODUCT_REMOVED_FROM_CART = 'PRODUCT_REMOVED_FROM_CART';
export const PRODUCTS_REMOVED_FROM_CART = 'PRODUCTS_REMOVED_FROM_CART';

export const THEME_PICKER_TOGGLE = 'THEME_PICKER_TOGGLE';

export const PRODUCT_TOGGLE_WISHLIST = 'PRODUCT_TOGGLE_WISHLIST';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
